### ISSUE TITLE
Add http support to the WASI provider

### ISSUE THREAD

**Issue by thomastaylor312** [krustlet/krustlet#598]
We need to add support for the [experimental HTTP library](https://github.com/deislabs/wasi-experimental-http/) in the wasi provider before we hit 1.0. This should be fairly simple and only involve adding it into the linker as shown in the documentation.

This work should also include an update to one of our existing demos or a new one to showcase the new functionality

**Comment by radu-matei** [comment]
One thing we should probably discuss here is how to handle allowed domains.
Specifically, the library expects a required list of domains where guest modules are allowed to make requests to, and if `None` is passed, all requests will be rejected.

That is a per module instantiation setting, so I assume it would have to be set by the pod definition?
Would that be an annotation?

**Comment by thomastaylor312** [comment]
Yeah, annotation is probably the best bet for the initial feature

**Comment by thomastaylor312** [comment]
Closed in #648
