### ISSUE TITLE
Rust security audit should be run regularly to catch outdated or orphaned dependencies

### ISSUE THREAD

**Issue by soenkeliebau** [krustlet/krustlet#640]
Krustlet currently does not appear to regularly run `cargo audit` to check for [security advisories](https://rustsec.org/) against its dependencies. 

We currently have an issue against our agent which is caused by a dependency that Krustlet pulls in
https://github.com/stackabletech/agent/issues/216 which was caused by our [daily audit check](https://github.com/stackabletech/agent/blob/main/.github/workflows/daily_security.yml).

It might be worth adding this or something similar to Krustlet as well.

**Comment by bacongobbler** [comment]
Marking this as a good enhancement to the project should someone feel interested learning how to set up an automated workflow.

https://docs.github.com/en/actions
https://github.com/marketplace/actions/rust-audit-check
