### ISSUE TITLE
bootstrapping fails if using filepath to CA instead of raw content

### ISSUE THREAD

**Issue by alexeldeib** [krustlet/krustlet#642]
this is fairly minor, but kind of annoying when you need to inject the CA content into the file, and they might technically be coming from different sources

https://github.com/deislabs/krustlet/blob/9efb832edb288ba86822bd62e80e3f9f5e68e37b/crates/kubelet/src/bootstrapping/mod.rs#L70

It'd be nice if this could try to check for either field (certificate_authority or certificate_authority_data), read the file content if it's the former, and then use whatever it found (or fail if neither).

**Comment by VishnuJin** [comment]
@thomastaylor312 @bacongobbler I would like to work on this issue. Any suggestions please ?

**Comment by thomastaylor312** [comment]
You'll need to add a small block of code there to see if `certificate_authority` is set and use it instead of `certificate_authority_data`

**Comment by VishnuJin** [comment]
@thomastaylor312 thought so. wanted to be sure so I don't do anything stupid. 
Will give this a try shortly !!
