### ISSUE TITLE
what is the key scenarios for wasm workloads deployed by krustlet?

### ISSUE THREAD

**Issue by flyflypeng** [krustlet/krustlet#672]
😀 This is an open discussion about the key scenarios or usercases for wasm workload, why do we eagerly want to deploy the workload with wasm format on Kubernetes by krustlet?

For example, today we are used to deploy micro-service on Kubernetes with container and service-mesh, which is a good solution to solve the micro-service execution environment problem and service-to-service communication problem, so what are the advantages of wasm under micro-service scenario? 
**Security?** Maybe container or kata-container security container is sufficient;
**Low memory footprint?** Maybe the micro-service scenario is not memory-resource sensitive, because the data center has sufficient memory resources. 
**Startup?** micro-service is a long-time running job, startup time is not so important.

**Comment by RaananHadar** [comment]
I have two common use cases to chip in:
The first is edge computing and IOT, an edge cluster has multiple use cases competing for resources. Lets assume I have multiple inferencing algorithms made by different teams that need to share a single cluster using industrial single board computers and most probably Jetson class GPUs for deep learning applications. **A jetson NX has 8GB of RAM.** Now, machine learning containers can get pretty big (multiple GB) to the level there isn't enough memory on a single node to allow more than one algorithm to use the node at the same time, and k8s will have to delete and pull a different image when it wants to switch an algorithm...having a low footprint can also enable squeezing more modern capabilities into the cluster, such as freeing RAM to be able to squeeze in decent monitoring such as basic GPU monitoring or a decent message queue for example...  So reducing footprint can be the difference between having a system which with a single service or multiple services and richer functionality such as monitoring, which is a very big deal. Startup time can also be very interesting here: In cases where you want context switch to a different configuration, startup time becomes important too.

The second one might surprise you but its where I am most fascinated about krustlet... **krustlet allows to deploy k8s pretty much anywhere.** For example, with krustlet I can deploy binaries which used to run only on linux and run them on windows machines at user level. With containers you need HyperV and WSL which isn't gurranteed on older windows server machines or on-prem enterprise windows development workstations. For example, [k3s doesn't have good windows support yet](https://github.com/k3s-io/k3s/issues/114), even though there is a good need for that. So I really think krustlet allows you to deploy light, user level k8s clusters on any operating system, for development and even production is going to be really cool.

**Comment by bacongobbler** [comment]
Thanks for sharing your thoughts @RaananHadar.

I wrote an article on the strengths of WebAssembly when we first introduced the project: https://deislabs.io/posts/introducing-krustlet/

A few other links to related articles can be found at our blog: https://deislabs.io/tags/krustlet/

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
