### ISSUE TITLE
Move oci-distribution to its own repository

### ISSUE THREAD

**Issue by bacongobbler** [krustlet/krustlet#690]
A number of community members have asked if oci-distribution can be maintained as a separate project so that it can cut new releases independently from the krustlet project. Moving the source code into its own repository under the krustlet org would be the simplest option.

To be completed prior to #616 so that a new release can be cut from the new repository

**Comment by flavio** [comment]
Thanks a lot for that! :heart:

**Comment by bacongobbler** [comment]
Can be closed now that #695 has been merged.
