### ISSUE TITLE
Kubelet build error

### ISSUE THREAD

**Issue by rickrain** [krustlet/krustlet#706]
I'm trying to build the sample from [here](https://docs.rs/kubelet/1.0.0-alpha.1/kubelet/index.html) and getting the following errors.  I understand this is not a full example, but was still expecting it to build. This is from the latest alpha build, but I've also tried using the last stable build and get the same errors.

```
   Compiling kubelet v1.0.0-alpha.1
error[E0599]: no function or associated item named `new_immediate` found for trait object `dyn Watcher` in the current scope
  --> /home/tinyedge/.cargo/registry/src/github.com-1ecc6299db9ec823/kubelet-1.0.0-alpha.1/src/fs_watch/mod.rs:39:56
   |
39 |         let mut watcher: RecommendedWatcher = Watcher::new_immediate(move |res| {
   |                                                        ^^^^^^^^^^^^^ function or associated item not found in `dyn Watcher`

error[E0308]: mismatched types
  --> /home/tinyedge/.cargo/registry/src/github.com-1ecc6299db9ec823/kubelet-1.0.0-alpha.1/src/fs_watch/mod.rs:46:23
   |
37 |     pub fn new<P: AsRef<Path>>(path: P) -> anyhow::Result<Self> {
   |                - this type parameter
...
46 |         watcher.watch(path, RecursiveMode::NonRecursive)?;
   |                       ^^^^ expected `&std::path::Path`, found type parameter `P`
   |
   = note:   expected reference `&std::path::Path`
           found type parameter `P`

Some errors have detailed explanations: E0308, E0599.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `kubelet` due to 2 previous errors
```

I've tried this on Ubuntu 20.04 and 21.10 and getting the same result.

My `Cargo.toml` contains the following:

```
[package]
name = "my-kubelet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kubelet = "1.0.0-alpha.1"
tokio = "1.14.0"
```

Appreciate any help to get a minimal build working as I'm new to this project and Rust.

**Comment by rickrain** [comment]
Looks like this is the result of [this PR](https://github.com/notify-rs/notify/pull/336/files) in the `notify` crate dependency.  If there are not objections, I'll submit a PR to address these changes.

**Comment by bacongobbler** [comment]
That would be wonderful. Thank you!

**Comment by rickrain** [comment]
@bacongobbler, it appears you already made the needed changes [here](https://github.com/krustlet/krustlet/pull/694/files).  However, it's not reflecting correctly in my cargo registries when I add `kubelet` as a dependency.  As a sanity check, I deleted and re-imported the registries based on my project dependencies.  It's not picking up the latest code for the `kubelet` crate.  Any ideas on why I'm not getting the latest `kubelet` code?

**Comment by bacongobbler** [comment]
https://github.com/krustlet/krustlet/blob/a303840c1fd86f2e07f687be47a137be2ecfd326/.github/workflows/release.yml#L146-L149

**Comment by rickrain** [comment]
OK, that makes sense.  Are there any thoughts to splitting `kubelet` out into a separate repo so `kubelet` and `krustlet` can have independent release cadences?

In the meantime, I suppose specifying a git dependency in my `Cargo.toml` would be the way to go.  Would you agree or is there a better alternative?

**Comment by bacongobbler** [comment]
I'd be okay with moving it to a separate repository like we did with oci-distribution and krator. I don't have the time to do that, but I'd be supportive of that effort.

> In the meantime, I suppose specifying a git dependency in my `Cargo.toml` would be the way to go

Yes.

**Comment by rickrain** [comment]
@bacongobbler , I created #707 to capture this conversation and closing this issue.
