### ISSUE TITLE
Provide an example about how to build a rocket project to wasm?

### ISSUE THREAD

**Issue by fanux** [krustlet/krustlet#709]
Using krustlet to run a HTTP server. 

If an application using rocket as HTTP framework and diesel as ORM, how to build it to wasm?

**Comment by radu-matei** [comment]
Hi, @fanux.
Currently, you are unable to compile a program that uses networking sockets to WebAssembly — this includes HTTP servers.

See https://github.com/WebAssembly/WASI/pull/312 and https://radu-matei.com/blog/towards-sockets-networking-wasi/ for a write-up of the status for the networking APIs in WASI.

The workaround for writing HTTP handlers in WebAssembly is by using Wagi (or something like it) — https://github.com/deislabs/wagi, where the underlying runtime handles the actual HTTP listener and server, and passes the request data to a WebAssembly module.
You can use it today with Krustlet by following  — https://github.com/deislabs/krustlet-wagi-provider

Closing now, as there isn't anything we can do on the Krustlet side, but feel free to reopen if you think there is something we can improve here.

Thanks!

**Comment by thangchung** [comment]
We might use Dapr with `wasi-experimental-http` to work around with this model for networking interface like this article https://www.alibabacloud.com/blog/webassembly-%2B-dapr-%3D-next-generation-cloud-native-runtime_598222 too
