### ISSUE TITLE
Some pod conditions are missing when using "kubectl describe" command

### ISSUE THREAD

**Issue by ln23415** [krustlet/krustlet#715]
Hi guys,  when I use `kubectl describe` to display pod information, in "Conditions" section I got:
```
Conditions:
  Type           Status
  PodScheduled   True 
```
while in normal pod workload I will got output like below:
```
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
```
Can we do something to fix it ? Thanks!

**Comment by bacongobbler** [comment]
https://github.com/krustlet/krustlet/blob/2e483ea9a01c43d407df85c9079cab99fe01c06c/crates/kubelet/src/pod/status.rs#L153

**Comment by bacongobbler** [comment]
https://github.com/krustlet/krustlet/blob/2e483ea9a01c43d407df85c9079cab99fe01c06c/crates/kubelet/src/pod/status.rs#L209-L210
