### ISSUE TITLE
Trouble initializing krustlet with minikube

### ISSUE THREAD

**Issue by manuschillernordlb** [krustlet/krustlet#719]
I am having trouble installing krustlet with minikube.

Steps: 
* start minikube: `minikube start --driver=hyperkit --cpus=4 --memory=8192`
* downloaded `https://krustlet.blob.core.windows.net/releases/krustlet-v1.0.0-alpha.1-macos-amd64.tar.gz`, extracted the contents and copied `krustlet-wasi` to `/usr/local/bin`
* following the steps from https://docs.krustlet.dev/howto/bootstrapping/:
  * `bash <(curl https://raw.githubusercontent.com/krustlet/krustlet/main/scripts/bootstrap.sh)`
  * `KUBECONFIG=~/.krustlet/config/kubeconfig krustlet-wasi --port 3000 --bootstrap-file ./bootstrap.conf`

Result:  
```
> Error: ApiError: the server could not find the requested resource: NotFound (ErrorResponse { status: "Failure", message: "the server could not find the requested resource", reason: "NotFound", code: 404 })

Caused by:
    the server could not find the requested resource: NotFound
```
Versions:
minikube: v1.25.1 on Darwin 12.3
krustlet: v1.0.0-alpha.1

Unfortunately, I don't know how I would debug this any further. Happy to help with any further information!

**Comment by bacongobbler** [comment]
Hi @manuschillernordlb. Have you had a chance to look at previously open issues? I noticed https://github.com/krustlet/krustlet/issues/699 and https://github.com/krustlet/krustlet/issues/680 report the same issue. Perhaps you're running into the same issues they were.

**Comment by manuschillernordlb** [comment]
bulding from main manually and running the created binary fixed the problem - thanks!
